
package client;

/*
 * THIS FILE HOLDS THE CHEESE CLASS, PACMAN'S OBJECTIVE. THERE ARE TWO TYPES OF 
 * CHEESE: SMALL AND LARGE. THESE WILL BE DISPERSED THROUGHOUT THE GAME MAZE 
 * UNIFORMLY.
 */

public class Cheese {
    
}
