
package client;

/*
 * THE HUD CLASS CONTAINS ALL OF THE COMPONENTS OF THE GAME HUD. THIS INCLUDES
 * LIVES, MAPS, TIME, GRAPHICS, ETC. ADDITIONAL CLASSES MAY BE CREATED FOR THESE 
 * INDIVIDUAL COMPONENTS IF IT IS REASONABLE.
 */

public class HUD {
    
}
