
package client;

/*
 * THIS IS THE GHOST CLASS - EVIL AS IT IS. HERE IS THE CREATION AND INITIALIZATION
 * OF THE GHOST OBJECT (GEOMETRIES, MATERIALS, STATS, CONTROLS, ETC.)
 */

public class Ghost {
    
}
