
package client;

/*
 * THIS IS THE ALL-IMPORTANT PACMAN CLASS. THIS HANDLES THE CREATION AND INITIALIZATION
 * OF THE PACMAN OBJECT (GEOMETRY, MATERIALS, CONTROLS, LIVES, ETC)
 */

public class Pacman {
    
}
