
package client;

/*
 * IT MIGHT MAKE SENSE TO HOLD ALL PLAYER METADATA IN A PLAYER CLASS.
 * THIS INCLUDES ROLE, POINTS, NAME, LIVES, OTHER INFO, ETC. THIS CAN BE AN 
 * OBJECT WE UPDATE BETWEEN THE SERVER AND CLIENT.
 */

public class Player {
    
}
